name: e2e tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: test
        run: make e2e-test
      - name: upload failed test artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: testlogs
          path: /tmp/*-e2etests*/*
