name: e2e tests

on:
  push:
  pull_request:

env:
  ECS_PRESERVE_E2E_TEST_LOGS: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: pretest
        run: |
          ip link show
          sudo ip link add eth1 type dummy
          ip link show
      - name: test
        run: make e2e-test
      - name: upload failed test artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: testlogs
          path: /tmp/*-e2eTests-*/*
